
### `pyproject.toml`
```toml
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "digital_workforce"
version = "0.1.0"
requires-python = ">=3.10"
